name: CMake tests with multiple compilers

on:
  push:
    branches: [ "new_pipeline_tests" ]
  pull_request:
    branches: [ "new_pipeline_tests" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: system
            compiler_type: g++
          - compiler: intel-oneapi-compilers
            compiler_type: icpx
          - compiler: intel-oneapi-compilers
            compiler_type: icpc
          - compiler: cuda
            compiler_type: nvcc

    steps:
      - uses: actions/checkout@v4

      - name: Set up Spack
        uses: spack/setup-spack@v2

      - name: Cache Spack store
        uses: actions/cache@v3
        with:
          path: ~/.spack
          key: ${{ runner.os }}-spack-${{ matrix.compiler }}

      - name: Install compilers via Spack
        if: matrix.compiler != 'system' && matrix.compiler != 'cuda'
        run: |
          spack install ${{
            matrix.compiler
          }}
          spack load --sh ${{
            matrix.compiler
          }}
          spack compiler find

      - name: Set compiler environment variable
        run: |
          if [[ "${{ matrix.compiler }}" == "system" ]]; then
            echo "CXX=$(which g++)" >> $GITHUB_ENV
            echo "CUDA=" >> $GITHUB_ENV
          elif [[ "${{ matrix.compiler_type }}" == "icpx" ]]; then
            echo "CXX=$(spack location -i intel-oneapi-compilers)/compiler/latest/linux/bin/icpx" >> $GITHUB_ENV
            echo "CUDA=" >> $GITHUB_ENV
          elif [[ "${{ matrix.compiler_type }}" == "icpc" ]]; then
            echo "CXX=$(spack location -i intel-oneapi-compilers)/compiler/latest/linux/bin/intel64/icpc" >> $GITHUB_ENV
            echo "CUDA=" >> $GITHUB_ENV
          elif [[ "${{ matrix.compiler_type }}" == "nvcc" ]]; then
            echo "CXX=$(which g++)" >> $GITHUB_ENV
            echo "CUDA=/usr/local/cuda/bin/nvcc" >> $GITHUB_ENV
          fi

      - name: Show Compilers
        run: echo "Using CXX = ${CXX}"
        run: echo "Using CUDA = ${CUDA}"

      - name: CMake configure SMAX
        run: |
          echo "CMake configure SMAX pwd = $(pwd)"
          mkdir smax_build && cd smax_build
          cmake .. \
            -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install/ \
            -DCMAKE_CXX_COMPILER=$CXX \
            -DCMAKE_CUDA_COMPILER=$CUDA
          echo "CMake configure SMAX INSTALLING TO = $(realpath ${{github.workspace}}/install/)"

      - name: Build & install SMAX
        working-directory: smax_build
        run: |
          echo "Build & install SMAX pwd = $(pwd)"
          make -j
          make install

      - name: CMake configure Tests
        working-directory: examples
        run: |
          echo "CMake configure Tests pwd = $(pwd)"
          echo "CMake configure Tests ${{github.workspace}}/install/ = $(realpath ${{github.workspace}}/install/)"
          mkdir tests_build && cd tests_build
          cmake .. \
            -DCMAKE_PREFIX_PATH=${{github.workspace}}/install/ \
            -DCMAKE_CXX_COMPILER=$CXX \
            -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc


      - name: Build Tests
        working-directory: examples/tests_build
        run: make -j          

      - name: Run Tests
        working-directory: examples/tests_build/tests/
        run: |
          chmod +x ./run_tests
          ./run_tests