name: CMake tests with multiple compilers

on:
  push:
    branches: [ "new_pipeline_tests" ]
  pull_request:
    branches: [ "new_pipeline_tests" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: system
            compiler_type: cxx
          # - compiler: intel@15.0.6
          #   compiler_id: INTEL
          # - compiler: nvhpc@22.3
          #   compiler_id: NVHPC

    steps:
      - uses: actions/checkout@v4

      - name: Set up Spack
        uses: spack/setup-spack@v2

      - name: Cache Spack store
        uses: actions/cache@v3
        with:
          path: ~/.spack
          key: ${{ runner.os }}-spack-${{ matrix.compiler }}

      - name: Install compiler via Spack
        if: matrix.compiler != 'system'
        run: spack install ${{ matrix.compiler }}

      - name: Load compiler into env
        run: |
          if [[ "${{ matrix.compiler }}" != "system" ]]; then
            spack load ${{ matrix.compiler }}
          fi
          echo "CXX=$(which g++)" >> $GITHUB_ENV

      - name: Show C++ compiler
        run: Using CXX = $CXX

      - name: CMake configure SMAX
        run: |
          mkdir smax_build && cd smax_build
          cmake .. \
            -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_CXX_COMPILER=$CXX

      - name: Build & install SMAX
        run: |
          cd smax_build/
          make -j
          make install

      - name: CMake configure Tests
        run: |
          cd examples/
          mkdir tests_build && cd tests_build
          cmake .. \
            -DCMAKE_PREFIX_PATH=../../install -DCMAKE_CXX_COMPILER=$CXX

      - name: Build Tests
        run: |
          cd examples/tests_build/
          make -j

      - name: Run Tests
        run: |
          cd examples/tests_build/
          chmod +x ./run_tests
          ./run_tests