name: CMake on a single platform

on:
  push:
    branches: [ "master", "cuda_fix" ]
  pull_request:
    branches: [ "master", "cuda_fix" ]

jobs:
  buildLibrary_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure build
      run: |
        mkdir ${{github.workspace}}/build 
        cd ${{github.workspace}}/build
        cmake .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Release

    - name: Make
      working-directory: ${{github.workspace}}/build
      run: make install

    - uses: actions/upload-artifact@v4
      with: 
        name: install-dir
        path: ${{github.workspace}}/install/
 
  buildTests_release:
    needs: buildLibrary_release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: install-dir
          path: ${{github.workspace}}/install

      - name: CMake and make
        run: |
          cd examples
          mkdir build && cd build
          cmake .. -DCMAKE_PREFIX_PATH=../../install -DCMAKE_BUILD_TYPE=Release
          make -j

      - uses: actions/upload-artifact@v4
        with: 
          name: tests
          path: ${{github.workspace}}/examples/build/tests/

  runTests_release:
    needs: buildTests_release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: install-dir
          path: ${{github.workspace}}/install
      - uses: actions/download-artifact@v4
        with:
          name: tests
          path: ${{github.workspace}}/run_tests

      - name: Execute Tests
        run: |
          cd run_tests
          chmod +x ./run_tests
          ./run_tests

  buildLibrary_debug:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure build
      run: |
        mkdir ${{github.workspace}}/build 
        cd ${{github.workspace}}/build
        cmake .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Debug

    - name: Make
      working-directory: ${{github.workspace}}/build
      run: make install

    - uses: actions/upload-artifact@v4
      with: 
        name: install-dir
        path: ${{github.workspace}}/install/
 
  buildTests_debug:
    needs: buildLibrary_debug
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: install-dir
          path: ${{github.workspace}}/install

      - name: CMake and make
        run: |
          cd examples
          mkdir build && cd build
          cmake .. -DCMAKE_PREFIX_PATH=../../install -DCMAKE_BUILD_TYPE=Debug
          make -j

      - uses: actions/upload-artifact@v4
        with: 
          name: tests
          path: ${{github.workspace}}/examples/build/tests/

  runTests_debug:
    needs: buildTests_debug
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: install-dir
          path: ${{github.workspace}}/install
      - uses: actions/download-artifact@v4
        with:
          name: tests
          path: ${{github.workspace}}/run_tests

      - name: Execute Tests
        run: |
          cd run_tests
          chmod +x ./run_tests
          ./run_tests
