name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure build
      run: |
        mkdir ${{github.workspace}}/build 
        cd ${{github.workspace}}/build
        cmake .. -DCMAKE_INSTALL_PREFIX=../install

    - name: Make
      working-directory: ${{github.workspace}}/build
      run: make install

    - uses: actions/upload-artifact@v4
      with: 
        name: install-dir
        path: ${{github.workspace}}/install/
 
  build_test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: install-dir
          path: ${{github.workspace}}/install

      - name: CMake and make
        run: |
          cd examples
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=../../install
          make

    - uses: actions/upload-artifact@v4
      with: 
        name: tests
        path: ${{github.workspace}}/examples/build/tests/

  run_test:
    needs: build_test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: tests
          path: ${{github.workspace}}/run_tests

      - name: Execute Tests
        run: |
          cd run_tests
          ./run_tests
